spring.application.name=EventManagement

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/event-management-boot?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.jpa.show-sql=true

spring.jackson.date-format=dd/MM/yyyy
spring.jackson.time-zone=GMT

# Enable second-level cache
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.use_query_cache=true

# Set the cache provider to EHCache
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory

# Optionally configure the cache settings for the cache provider (e.g., EHCache)
spring.cache.type=ehcache
